# Site settings
title: Kevin Fusco - Homepage
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kevin Fusco
user_description: I am a senior biomedical engineering student at Florida International University with a passion for lifting weights and programming. 
                  Below you can see some of the technologies currently within my skillset as well as projects I've worked on. If you would like to contact me, please
                  feel free to message me on one of the platforms displayed above.
user_title: 
email: dev.kevin.f@gmail.com
twitter_username: lorem_ipsum
github_username:  nivex28
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
